service: s3-manager-server

custom:
  S3_BUCKET_NAME: "s3-manager-bucket"

provider:
  name: aws
  runtime: nodejs10.x
     
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-iam-roles-per-function

functions:
  upload-on-s3: ${file(./uploadOnS3/serverless.functions.yml):upload-on-s3}   