service: s3-manager-server

custom:
  S3_BUCKET_NAME: "s3-manager-bucket"
  REGION: "us-east-2"

provider:
  name: aws
  runtime: nodejs10.x
     
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-iam-roles-per-function

functions:
  upload-base-64: ${file(./uploadBase64/serverless.functions.yml):upload-base-64}
  get-upload-persigned-url: ${file(./getUploadPresignedUrl/serverless.functions.yml):get-upload-persigned-url}
  list-objects: ${file(./listObjects/serverless.functions.yml):list-objects}
  delete-object: ${file(./deleteObject/serverless.functions.yml):delete-object}